### ISSUE TITLE
Choose what games to upload when uploading power.log file

### ISSUE THREAD

**Issue by sebastientromp** [Zero-to-Heroes/zerotoheroes.com#67]

**Comment by mmascher** [comment]
I think there are two use cases:
1) In arena you might be interested in the whole run and you may want to select all the games
2) In constructed, 99% of the time you are only interested in the last game (and maybe in arena too!), I really think we need a button to optimize that. Like "Upload the last game" nearby "Upload". This way with one click (and one to select the file) I am done. Otherwise selecting the power.log, waiting that it is uploaded, select the games, and confirm becomes really tedious!

**Comment by sebastientromp** [comment]
Makes sense! I'll be looking at the options I have and come back to you here

**Comment by sebastientromp** [comment]
We're moving away from Power.log and want to favor using auto uploads (for now Overwolf). Please don't hesitate to reopen it in case this is still needed
